spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: product-client
            client-secret: product-secret
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/product-realm
            token-uri: http://keycloak:8080/realms/product-realm/protocol/openid-connect/token

resource-server:
  url: http://resource-server:8080